services:
  postgres:
    image: postgres:14-alpine
    container_name: starterkit-postgres
    profiles:
      - db
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - db-net
    restart: unless-stopped

  redis:
    image: redis:6.2-alpine
    container_name: starterkit-redis
    profiles:
      - db
      - worker
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server /redis.conf --requirepass ${REDIS_PASSWORD}
    volumes:
      - ../data/redis:/data
      - ./redis.conf:/redis.conf
    networks:
      - db-net
      - queue-net

networks:
  db-net:
  queue-net: